replicaCount: 1
image:
  repository: cool-example-api
  tag: latest
environment: default
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
ingress:
  enabled: false
  className: traefik
  host: ""
  path: /api